### ISSUE TITLE
Unable to instantiate service com.tns.notifications.NotificationIntentService

### ISSUE THREAD

**Issue by pacear10** [NativeScript/sample-android-background-services#10] opened 2017-01-24 16:46 UTC
Today I am running the project for background services

Still showing the same error, what must be done to take the changes made three days ago and stop displaying the error message?
Thank you.

`An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to instantiate service com.tns.notifications.NotificationIntentService: java.lang.InstantiationException: can't instantiate class com.tns.notifications.NotificationIntentService; no empty constructor
at android.app.ActivityThread.handleCreateService(ActivityThread.java:2641)
at android.app.ActivityThread.access$1600(ActivityThread.java:153)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1329)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5227)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:562)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.InstantiationException: can't instantiate class com.tns.notifications.NotificationIntentService; no empty constructor
at java.lang.Class.newInstanceImpl(Native Method)
at java.lang.Class.newInstance(Class.java:1319)
at android.app.ActivityThread.handleCreateService(ActivityThread.java:2638)
... 10 more`

**Comment by petekanev** [comment] 2017-01-24 17:13
Duplicate of https://github.com/NativeScript/sample-android-background-services/issues/2

**Closed as completed by petekanev** 2017-01-24 17:13 UTC
