### ISSUE TITLE
Cannot read property 'NotificationIntentService' of undefined

### ISSUE THREAD

**Issue by Taremeh** [NativeScript/sample-android-background-services#23] opened 2018-01-24 23:26 UTC
Hi! I'm using Angular + Nativescript with Android (everything on newest version).
Even though I tried to implement everything as it is in this sample + installing nativescript-android-utils, I'm still getting this error:

```
JS: onReceive from alarm, starting notification service! thread: main
System.err: java.lang.RuntimeException: Unable to start receiver com.tns.broadcastreceivers.NotificationEventReceiver: com.tns.NativeScriptException: 
System.err: Calling js method onReceive failed
System.err: 
System.err: TypeError: Cannot read property 'NotificationIntentService' of undefined
System.err: File: "file:///data/data/com.apphoven.apphovenAlpha/files/app/pages/piece/piece-recorder/background-service/NotificationEventReceiver.js, line: 23, column: 58
System.err: 
System.err: StackTrace: 
System.err: 	Frame: function:'createIntentStartNotificationService', file:'file:///data/data/com.apphoven.apphovenAlpha/files/app/pages/piece/piece-recorder/background-service/NotificationEventReceiver.js', line: 23, column: 59
System.err: 	Frame: function:'onReceive', file:'file:///data/data/com.apphoven.apphovenAlpha/files/app/pages/piece/piece-recorder/background-service/NotificationEventReceiver.js', line: 7, column: 29
System.err: 
System.err: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3313)
System.err: 	at android.app.ActivityThread.-wrap20(ActivityThread.java)
System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1719)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
System.err: 	at android.os.Looper.loop(Looper.java:154)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6692)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
System.err: Caused by: com.tns.NativeScriptException: 
System.err: Calling js method onReceive failed
System.err: 
System.err: TypeError: Cannot read property 'NotificationIntentService' of undefined
System.err: File: "file:///data/data/com.apphoven.apphovenAlpha/files/app/pages/piece/piece-recorder/background-service/NotificationEventReceiver.js, line: 23, column: 58
System.err: 
System.err: StackTrace: 
System.err: 	Frame: function:'createIntentStartNotificationService', file:'file:///data/data/com.apphoven.apphovenAlpha/files/app/pages/piece/piece-recorder/background-service/NotificationEventReceiver.js', line: 23, column: 59
System.err: 	Frame: function:'onReceive', file:'file:///data/data/com.apphoven.apphovenAlpha/files/app/pages/piece/piece-recorder/background-service/NotificationEventReceiver.js', line: 7, column: 29
System.err: 
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err: 	at com.tns.broadcastreceivers.NotificationEventReceiver.onReceive(NotificationEventReceiver.java:14)
System.err: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3306)
System.err: 	... 8 more
ActivityManager: Process com.apphoven.apphovenAlpha (pid 22890) has died(148,1524)
ActivityManager: cleanUpApplicationRecord -- 22890

```

This is the NotificationEventReceiver.js:

```
android.support.v4.content.WakefulBroadcastReceiver.extend("com.tns.broadcastreceivers.NotificationEventReceiver", {
    onReceive: function (context, intent) {
        var action = intent.getAction();
        var serviceIntent = null;
        if ("ACTION_START_NOTIFICATION_SERVICE" == action) {
            console.log("onReceive from alarm, starting notification service! thread: " + java.lang.Thread.currentThread().getName());
            serviceIntent = createIntentStartNotificationService(context);
        } else if ("ACTION_DELETE_NOTIFICATION" == action) {
            console.log("onReceive delete notification action, starting notification service to handle delete");
            serviceIntent = createIntentDeleteNotification(context);
        }

        if (serviceIntent) {
            android.support.v4.content.WakefulBroadcastReceiver.startWakefulService(context, serviceIntent);
        }
    }
})

var Intent = android.content.Intent;


function createIntentStartNotificationService(context) {
    var intent = new Intent(context, com.tns.notifications.NotificationIntentService.class);
    intent.setAction("ACTION_START");
    return intent;
}

function createIntentDeleteNotification(context) {
    var intent = new Intent(context, com.tns.notifications.NotificationIntentService.class);
    intent.setAction("ACTION_DELETE");
    return intent;
}
```

AndroidManifest.xml:
```
...

<service  android:name="com.tns.notifications.NotificationIntentService"
            android:enabled="true"
            android:exported="false" />

        <receiver android:name="com.tns.broadcastreceivers.NotificationEventReceiver" />
        <receiver android:name="com.tns.broadcastreceivers.NotificationServiceStarterReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
                <action android:name="android.intent.action.TIMEZONE_CHANGED" />
                <action android:name="android.intent.action.TIME_SET" />
            </intent-filter>
        </receiver>
	</application>
</manifest>

```
I really tried everything to get it work, but I can't find the cause... Please help 😅

**Comment by cesarvega** [comment] 2018-01-25 20:33
Hey @Taremeh  I hve the same issue I even down grade my tns-core-services to v.3.3.0 and still says 
**Cannot read property 'IntentService' of undefined**

**_because this is undefined com.pip3r4o.android.app = _undefined_**

**Comment by cesarvega** [comment] 2018-01-25 20:35
I your case **System.err: TypeError: Cannot read property 'NotificationIntentService' of undefined
System.err: File: "file:///data/data/com.apphoven.apphovenAlpha/files/app/pages/piece/piece-recorder/background-service/NotificationEventReceiver.js, line: 23, column: 58**

this is because you have to add this to the AndroidManifest.xml inside the App_Resources/ android/AndroidManifest.xml
here is my file.

`<?xml version="1.0" encoding="utf-8"?>
<manifest
    xmlns:android="http://schemas.android.com/apk/res/android" package="__PACKAGE__" android:versionCode="1" android:versionName="1.0">
    <supports-screens android:smallScreens="true" android:normalScreens="true" android:largeScreens="true" android:xlargeScreens="true" />
    <uses-sdk android:minSdkVersion="17" android:targetSdkVersion="__APILEVEL__" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />    
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-feature android:name="android.hardware.location.gps" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />


    <application android:name="com.tns.NativeScriptApplication" 
        android:allowBackup="true" 
        android:hardwareAccelerated="false" 
        android:largeHeap="true" android:icon="@drawable/icon" 
        android:label="@string/app_name" android:theme="@style/AppTheme">
        <activity android:name="com.tns.NativeScriptActivity" 
            android:hardwareAccelerated="true" android:label="@string/title_activity_kimera" 
            android:configChanges="keyboardHidden|orientation|screenSize" 
            android:theme="@style/LaunchScreenTheme">
            <meta-data android:name="SET_THEME_ON_LAUNCH" android:resource="@style/AppTheme" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity android:name="com.tns.ErrorReportActivity" />
        <service
           android:name="com.tns.notifications.NotificationIntentService"
           android:enabled="true"
           android:exported="false" />
          
          <receiver android:name="com.tns.broadcastreceivers.NotificationEventReceiver" />
        <receiver android:name="com.tns.broadcastreceivers.NotificationServiceStarterReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
                <action android:name="android.intent.action.TIMEZONE_CHANGED" />
                <action android:name="android.intent.action.TIME_SET" />
            </intent-filter>
        </receiver>
      
    </application>
</manifest>`

**Comment by petekanev** [comment] 2018-01-26 08:09
@Taremeh did you install `nativescript-android-utils`?

The IntentService IS undefined, unless you install the `nativescript-android-utils` package, which is where the custom IntentService comes from!

**Comment by Taremeh** [comment] 2018-01-27 20:57
Why did you close it? Yes, as I said I have even installed the nativescript-android-utils...
And yes, as I said, I also included those lines into my AndroidManifesto. But it still doesn't work...

**Comment by Taremeh** [comment] 2018-01-27 21:18
More about the crash:

```
JS: onReceive from alarm, starting notification service! thread: main
System.err: java.lang.RuntimeException: Unable to start receiver com.tns.broadcastreceivers.NotificationEventReceiver: com.tns.NativeScriptException: 
System.err: Calling js method onReceive failed
System.err: 
System.err: TypeError: Cannot read property 'NotificationIntentService' of undefined
System.err: File: "file:///data/data/com.apphoven.apphovenAlpha/files/app/pages/piece/piece-recorder/background-service/NotificationEventReceiver.js, line: 23, column: 58
System.err: 
System.err: StackTrace: 
System.err: 	Frame: function:'createIntentStartNotificationService', file:'file:///data/data/com.apphoven.apphovenAlpha/files/app/pages/piece/piece-recorder/background-service/NotificationEventReceiver.js', line: 23, column: 59
System.err: 	Frame: function:'onReceive', file:'file:///data/data/com.apphoven.apphovenAlpha/files/app/pages/piece/piece-recorder/background-service/NotificationEventReceiver.js', line: 7, column: 29
System.err: 


......
```

**Comment by cesarvega** [comment] 2018-01-29 16:52
I did Install the nativescript-android-utils something i notice is the index.d.ts is empty when install via npm but if you download the source code from here witch it  does have a type definition code file index.d.ts, i try with that and still saying that my Instance method is undefined 
![capture](https://user-images.githubusercontent.com/1844897/35522875-826b289c-04eb-11e8-8bae-7e56769ae6d1.JPG)

**Comment by Taremeh** [comment] 2018-01-29 20:09
@cesarvega Yes, my index.d.ts was empty too. However downloading it from here and then adding it to my app manually did not help. Still same issue:

```
JS: onReceive from alarm, starting notification service! thread: main
System.err: java.lang.RuntimeException: Unable to start receiver com.tns.broadcastreceivers.NotificationEventReceiver: com.tns.NativeScriptException: 
System.err: Calling js method onReceive failed
System.err: 
System.err: TypeError: Cannot read property 'NotificationIntentService' of undefined
System.err: File: "file:///data/data/com.apphoven.apphovenAlpha/files/app/pages/settings/background-service/NotificationEventReceiver.js, line: 23, column: 58
System.err: 
System.err: StackTrace: 
System.err: 	Frame: function:'createIntentStartNotificationService', file:'file:///data/data/com.apphoven.apphovenAlpha/files/app/pages/settings/background-service/NotificationEventReceiver.js', line: 23, column: 59
System.err: 	Frame: function:'onReceive', file:'file:///data/data/com.apphoven.apphovenAlpha/files/app/pages/settings/background-service/NotificationEventReceiver.js', line: 7, column: 29
System.err: 
System.err: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3313)
System.err: 	at android.app.ActivityThread.-wrap20(ActivityThread.java)
System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1719)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
System.err: 	at android.os.Looper.loop(Looper.java:154)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6692)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
System.err: Caused by: com.tns.NativeScriptException: 
System.err: Calling js method onReceive failed
System.err: 
System.err: TypeError: Cannot read property 'NotificationIntentService' of undefined
System.err: File: "file:///data/data/com.apphoven.apphovenAlpha/files/app/pages/settings/background-service/NotificationEventReceiver.js, line: 23, column: 58
System.err: 
System.err: StackTrace: 
System.err: 	Frame: function:'createIntentStartNotificationService', file:'file:///data/data/com.apphoven.apphovenAlpha/files/app/pages/settings/background-service/NotificationEventReceiver.js', line: 23, column: 59
System.err: 	Frame: function:'onReceive', file:'file:///data/data/com.apphoven.apphovenAlpha/files/app/pages/settings/background-service/NotificationEventReceiver.js', line: 7, column: 29
System.err: 
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err: 	at com.tns.broadcastreceivers.NotificationEventReceiver.onReceive(NotificationEventReceiver.java:14)
System.err: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3306)
System.err: 	... 8 more
ActivityManager: Process com.apphoven.apphovenAlpha (pid 11321) has died(144,1448)
ActivityManager: cleanUpApplicationRecord -- 11321

```

**Comment by Taremeh** [comment] 2018-01-29 20:12
And: App randomly crashes with the same error, even though I didn't fire a new notification. So the notification seems to be floating around somewhere, but calling the "NotificationIntentService" kills the app and causes the crash.

**Comment by petekanev** [comment] 2018-01-30 08:03
@Taremeh @cesarvega I'll look into the problem, but meanwhile if I may ask, what device are you trying to run the application on? What API Level is the device? 

We've updated the sample in the `master` branch to use code compatible with Oreo, no longer using broadcast receivers, as those didn't seem to work on Android O and higher API levels.

**Comment by cesarvega** [comment] 2018-01-30 13:26
@Pip3r4o Hey thanks for your reply, I have minimum SDK 19 Target 25 I want use the background service cause the job scheduler dont fire for some reason if time is lower than 15 min and I need this running every 5 min. 


HERE is a link of the sample project with node_modules and everything  , is just 113 MB ready to tns debug android Please copy and paste the link to your browser 

https://drive.google.com/file/d/17DerexsCGYbpQaBETv3hgYdhA7It0Kpc/view?usp=sharing

![capture](https://user-images.githubusercontent.com/1844897/35568410-df4fa7bc-0596-11e8-8f24-6c3283b0dbba.JPG)

**Comment by petekanev** [comment] 2018-01-30 14:43
@cesarvega @Taremeh 

Following are the two test runs of the sample application. The first one is of the master branch, and the other is from the older code base - `implementation-prior-apiLevel21` branch.

Master branch, Emulator API 26 -
![bg-service-master-branch](https://user-images.githubusercontent.com/10464986/35571943-24219162-05dc-11e8-85b9-c5c9f353a43f.PNG)

The notification works on API 26 using the updated notification service.

implementation-prior-apiLevel21 branch, Emulators API 26 (left), and API 24 (right)
![bg-service-old-branch](https://user-images.githubusercontent.com/10464986/35571971-352b28ec-05dc-11e8-8518-bd36ad50decd.PNG)

The old notification service doesn't work on API 26, however it does work on API 24, as can be seen from the following screenshot
![image](https://user-images.githubusercontent.com/10464986/35572015-53ea58e8-05dc-11e8-9e6b-5689a5d748ad.png)

Please share a github repository with a sample where the issue can be reproduced reliably, so that I may test locally, and potentially get to the root of the problem.

**Comment by cesarvega** [comment] 2018-01-30 15:02
here is the sample @Pip3r4o  https://drive.google.com/open?id=1iWW8mYHwUSrsweMypVv_qs7rg-CjuFQU just got to the app.component.ts there is a  test(event){} where I put the code, I comment the intent service and leave the job scheduler with this time  builder.setPeriodic(3 * 60 * 1000); instead of  builder.setPeriodic(15 * 60 * 1000); and its no firing ... check the sample app I did install the utils via npm and then I updated with the master  my emulator API is 24 Genymotion

**Comment by petekanev** [comment] 2018-01-30 15:46
@cesarvega the code from `master` won't really work for your case because it targets devices running API 26 (Android N) and up. If you wish for the local notifications to work both for old and newer devices, then you will need to have both implementations in your code base. Using the JobService will work on devices as low as API 21.

Your code, inside the extended JobService, does log `"Job execution ..."` inside the `onStartJob()` callback, perhaps this is the desired behavior? Here's what it looks like on Emulator API 24. The results are similar on API 26 - the onStartJob fires.
![cesarvega](https://user-images.githubusercontent.com/10464986/35575519-3dd4db2e-05e5-11e8-9e7b-2a3e83b11f1d.PNG)


Also, please share the projects on github if possible, reviewing and contributing is a lot easier. Make sure to ignore uploading the `platforms`, `node_modules`, and `hooks` directories.

**Comment by cesarvega** [comment] 2018-01-30 15:57
@Pip3r4o yes it gets to that point where you log the Job Schedule, but try to repeat the job I never does, also I want to test the job every 10 second is that possible  **(  builder.setPeriodic(15 * 60 * 1000);**) I need to send a post to a server with the users location  once is inside this onStartJob function, since I cant repeat this IM trying the 15 min but not notification is coming up

**Comment by petekanev** [comment] 2018-01-30 16:08
@cesarvega your code does not contain anything related to notifications, as you've most likely stripped that. Therefore it is completely natural that you are not seeing notifications. 

JobInfo's builder's [setPeriodic](https://developer.android.com/reference/android/app/job/JobInfo.Builder.html#setPeriodic(long)) method will set an interval within which the scheduled job will execute **once**, you can try setting values lower than 15 minutes, but I can't tell you when, and if a job can be executed as often as every 10 seconds.

`builder.setPeriodic(15 * 60 * 1000);` in this sample, 15 is minutes, 60 is seconds withing a minute, and 1000 milliseconds within a second - the multiplication of all 3 values will result in the milliseconds equivalent of 15 minutes. Therefore if you wanted to try to run a job every 10 seconds (remember, there might be a software limitation that does not allow you to run a job that often), then the call to `setPeriodic` will look something like this: `builder.setPeriodic(10 * 1000);`

@cesarvega if your original problem, as stated in the github issue's title, has been resolved, please consider posting any future questions on the official forums at https://discourse.nativescript.org/

**Comment by cesarvega** [comment] 2018-01-30 18:18
Ok I see is working on 15 min I will test more and when I complete and make sure is working then I will share my solution thank you 

![capture](https://user-images.githubusercontent.com/1844897/35583501-20fb102e-05c0-11e8-8082-541c3004cdc9.JPG)

**Comment by fabiomela** [comment] 2018-03-16 09:28
@cesarvega 
Did you arrange the solution with **Nativescript+Angular** for **android**, with app closed and removed from the tray?
I still have an error just like:
`java.lang.RuntimeException: Unable to instantiate service com.tns.notifications.MyJobService: com.tns.NativeScriptException: Failed to create JavaScript extend wrapper for class 'com/tns/notifications/MyJobService'
03-15 11:36:33.150: W/System.err(16122): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3176)
03-15 11:36:33.150: W/System.err(16122): 	at android.app.ActivityThread.-wrap5(ActivityThread.java)
03-15 11:36:33.150: W/System.err(16122): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
03-15 11:36:33.150: W/System.err(16122): 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-15 11:36:33.150: W/System.err(16122): 	at android.os.Looper.loop(Looper.java:154)
03-15 11:36:33.150: W/System.err(16122): 	at android.app.ActivityThread.main(ActivityThread.java:6119)
03-15 11:36:33.150: W/System.err(16122): 	at java.lang.reflect.Method.invoke(Native Method)
03-15 11:36:33.150: W/System.err(16122): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
03-15 11:36:33.150: W/System.err(16122): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
03-15 11:36:33.150: W/System.err(16122): Caused by: com.tns.NativeScriptException: Failed to create JavaScript extend wrapper for class 'com/tns/notifications/MyJobService'
03-15 11:36:33.150: W/System.err(16122): 	at com.tns.Runtime.createJSInstanceNative(Native Method)
03-15 11:36:33.150: W/System.err(16122): 	at com.tns.Runtime.createJSInstance(Runtime.java:631)
03-15 11:36:33.150: W/System.err(16122): 	at com.tns.Runtime.initInstance(Runtime.java:606)
03-15 11:36:33.150: W/System.err(16122): 	at com.tns.notifications.MyJobService.<init>(MyJobService.java:7)
03-15 11:36:33.150: W/System.err(16122): 	at java.lang.Class.newInstance(Native Method)
03-15 11:36:33.150: W/System.err(16122): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3173)
03-15 11:36:33.150: W/System.err(16122): 	... 8 more`

@Pip3r4o  or @cesarvega Do you have any suggestion?

Thanks in advance

**Comment by NickIliev** [comment] 2018-06-27 08:29
The demo was updated and will currently work only on Android API 26 and above (as it is now using `NotificationChannel`). Closing this issue as it should no longer be reproducible (due to the new demo implementation)

**Closed as completed by NickIliev** 2018-06-27 08:29 UTC
